name: Checkstyle

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
  
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*.java,**/*.xml'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
          
      - name: Install Dependencies
        run: mvn install -DskipTests
        
      - name: Run Checkstyle on Changed Files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.txt
          mvn checkstyle:check \
            -Dcheckstyle.config.location=checkstyle.xml \
            -Dcheckstyle.includeResources=false \
            -Dcheckstyle.includeTestResources=false \
            -Dcheckstyle.includes=@changed_files.txt

      - name: Block PR on Checkstyle Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Checkstyle checks failed. Please fix the code formatting issues.')